# Ocultamos archivos internos – exportamos solo lo necesario
from .scraping import TEST, PRODUCTION
from .keywords import POSITIVE, NEGATIVE, EXPLICIT
from .scoring import WEIGHTS, PROXIMITY, SURFACE
from .selectors import LISTADO_ARTICULOS, LISTADO_ID_ATTR, LISTADO_PAGINA, FICHA_TITULO, FICHA_UBICACION, FICHA_PRECIO, FICHA_STATS_FECHA, FICHA_STATS_LINK, FICHA_BARRIO_MUN, FICHA_CARACT_BASIC, FICHA_CARACT_EXTRA, FICHA_MAPA_IMG

__all__ = [
    "TEST", "PRODUCTION",
    "POSITIVE", "NEGATIVE", "EXPLICIT",
    "WEIGHTS", "PROXIMITY", "SURFACE",
    "LISTADO_ARTICULOS", "LISTADO_ID_ATTR", "LISTADO_PAGINA",
    "FICHA_TITULO", "FICHA_UBICACION", "FICHA_PRECIO", "FICHA_STATS_FECHA", "FICHA_STATS_LINK", "FICHA_BARRIO_MUN", "FICHA_CARACT_BASIC", "FICHA_CARACT_EXTRA", "FICHA_MAPA_IMG"
]